@startuml Admin Update Report Settings
!theme cerulean

title "Admin Update Report Settings"

actor Admin
boundary "Audit Web Site" as WebSite
queue "Manual data Refresh Trigger" as DataRefreshQueue

Admin -> WebSite : Trigger Data Refresh
WebSite -> DataRefreshQueue : Queue data refresh

@enduml