# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tstate"
    key                  = "terraform.tfstate"
    resource_group_name  = "wapol-dev-rg-pbi-audit"
    storage_account_name = "wapoldevstpbiauditstate"
  }
}
